# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://blog.geuze.dev" # the url of your github pages

# site information used in page title, meta data etc.
title: Dré's Notebook
description: This repository contains all my try-out code, random things I encountered during my many hobbies or other learnings from home automation and networking. Welcome to my personal notebook 😄👋

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: André Geuze
author-bio: Cloud-native Software Developer  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
github: https://github.com/andregeuze
linkedin: https://www.linkedin.com/in/andregeuze
instagram: https://www.instagram.com/dre.unleashed
twitter: false
facebook: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
# google-analytics: G-WCRC1TC2V5

# Microsoft Clarity Analytics
microsoft-clarity: pxjeq2u2oq

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
