services:
  jekyll:
    build: .
    ports:
      - "4000:4000" # For the Jekyll server
      - "35729:35729" # For the livereload functionality
    volumes:
      - .:/app
    command: bundle exec jekyll serve --force_polling --drafts --verbose --host 0.0.0.0
