version: "3"

services:
  phptest:
    build: .
    image: phptest
    container_name: "phptest"
    environment:
      - ENVIRONMENT=development
      - MYSQL_DATABASE=second_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log
    ports: 
      - "80:80"